

IMPORTANT WARNING: Sequences Luzula_hitchcockii_14324 and Carex_cf_phaeocephala_14326 are exactly identical


IMPORTANT WARNING: Sequences Antennaria_umbrinella_14223 and Antennaria_umbrinella_14460 are exactly identical


IMPORTANT WARNING: Sequences Chaenactis_alpina_13579 and Chaenactis_alpina_13553 are exactly identical


IMPORTANT WARNING: Sequences Chaenactis_alpina_13579 and Chaenactis_alpina_14283 are exactly identical


IMPORTANT WARNING: Sequences Tonestus_lyallii_14308 and Selaginella_densa_14265 are exactly identical


IMPORTANT WARNING: Sequences Haplopappus_macronema_14342 and Ericameria_discoidea_14315 are exactly identical


IMPORTANT WARNING: Sequences Senecio_fremontii_14707 and Senecio_fremontii_14275 are exactly identical


IMPORTANT WARNING: Sequences Senecio_fremontii_14707 and Senecio_fremontii_14466 are exactly identical


IMPORTANT WARNING: Sequences Achillea_millefolium_var_alpicola_14287 and Achillea_millefolium_var_alpicola_14136 are exactly identical


IMPORTANT WARNING: Sequences Oxyria_digyna_14257 and Oxyria_digyna_14343 are exactly identical


IMPORTANT WARNING: Sequences Senecio_fremontii_14033 and Unknown_14135 are exactly identical


IMPORTANT WARNING: Sequences Juniperus_communis_14233 and Juniperus_communis_14031 are exactly identical

IMPORTANT WARNING
Found 12 sequences that are exactly identical to other sequences in the alignment.
Normally they should be excluded from the analysis.


A mixed model file with model assignments for undetermined
columns removed has already been printed to  file part.txt.reduced
Just in case you might need it, an alignment file with 
sequence duplicates removed is printed to file infile.txt.reduced


This is RAxML version 8.2.8 released by Alexandros Stamatakis on March 23 2016.

With greatly appreciated code contributions by:
Andre Aberer      (HITS)
Simon Berger      (HITS)
Alexey Kozlov     (HITS)
Kassian Kobert    (HITS)
David Dao         (KIT and HITS)
Sarah Lutteropp   (KIT and HITS)
Nick Pattengale   (Sandia)
Wayne Pfeiffer    (SDSC)
Akifumi S. Tanabe (NRIFS)
Charlie Taylor    (UF)


Alignment has 5651 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 72.34%

RAxML rapid bootstrapping and subsequent ML search

Using 6 distinct models/data partitions with joint branch length optimization



Executing 1000 rapid bootstrap inferences and thereafter a thorough ML search 

All free model parameters will be estimated by RAxML
ML estimate of 25 per site rate categories

Likelihood of final tree will be evaluated and optimized under GAMMA

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 881
Name: ITS
DataType: DNA
Substitution Matrix: GTR



Partition: 1
Alignment Patterns: 1101
Name: matK
DataType: DNA
Substitution Matrix: GTR



Partition: 2
Alignment Patterns: 222
Name: rbcL
DataType: DNA
Substitution Matrix: GTR



Partition: 3
Alignment Patterns: 585
Name: atpB
DataType: DNA
Substitution Matrix: GTR



Partition: 4
Alignment Patterns: 1099
Name: ndhF
DataType: DNA
Substitution Matrix: GTR



Partition: 5
Alignment Patterns: 1763
Name: trnTLF
DataType: DNA
Substitution Matrix: GTR




RAxML was called as follows:

raxmlHPC-HYBRID -T 4 -f a -N autoMRE -n sawtooth.concat.autoMRE.ML -s infile.txt -q part.txt -p 12345 -m GTRCAT -x 12345 



Time for BS model parameter optimization on Process 1: 17.883564 seconds

Time for BS model parameter optimization on Process 2: 20.098258 seconds

Time for BS model parameter optimization on Process 0: 17.968420 seconds

Time for BS model parameter optimization on Process 6: 21.206935 seconds

Time for BS model parameter optimization on Process 5: 20.771204 seconds

Time for BS model parameter optimization on Process 10: 19.361591 seconds

Time for BS model parameter optimization on Process 4: 21.351098 seconds

Time for BS model parameter optimization on Process 3: 20.328856 seconds

Time for BS model parameter optimization on Process 9: 19.673812 seconds

Time for BS model parameter optimization on Process 7: 20.955041 seconds

Time for BS model parameter optimization on Process 11: 20.432404 seconds

Time for BS model parameter optimization on Process 8: 19.256662 seconds
Bootstrap[168]: Time 71.035046 seconds, bootstrap likelihood -139412.351861, best rearrangement setting 10
Bootstrap[504]: Time 70.723774 seconds, bootstrap likelihood -143739.147890, best rearrangement setting 5
Bootstrap[420]: Time 72.634706 seconds, bootstrap likelihood -139293.960113, best rearrangement setting 6
Bootstrap[336]: Time 75.928572 seconds, bootstrap likelihood -139689.717400, best rearrangement setting 8
Bootstrap[840]: Time 75.980018 seconds, bootstrap likelihood -142340.676792, best rearrangement setting 10
Bootstrap[84]: Time 76.563546 seconds, bootstrap likelihood -139245.141682, best rearrangement setting 12
Bootstrap[0]: Time 77.995972 seconds, bootstrap likelihood -141049.340459, best rearrangement setting 13
Bootstrap[756]: Time 78.861472 seconds, bootstrap likelihood -137943.825331, best rearrangement setting 12
Bootstrap[588]: Time 79.761290 seconds, bootstrap likelihood -141402.853241, best rearrangement setting 15
Bootstrap[252]: Time 81.241538 seconds, bootstrap likelihood -138543.225518, best rearrangement setting 9
Bootstrap[924]: Time 83.112909 seconds, bootstrap likelihood -139747.690315, best rearrangement setting 9
Bootstrap[672]: Time 86.986228 seconds, bootstrap likelihood -136215.391505, best rearrangement setting 13
Bootstrap[169]: Time 39.504711 seconds, bootstrap likelihood -144787.515030, best rearrangement setting 13
Bootstrap[505]: Time 41.746893 seconds, bootstrap likelihood -142464.548572, best rearrangement setting 15
Bootstrap[841]: Time 37.929577 seconds, bootstrap likelihood -143597.108162, best rearrangement setting 6
Bootstrap[757]: Time 35.662468 seconds, bootstrap likelihood -140719.468787, best rearrangement setting 5
Bootstrap[589]: Time 34.987551 seconds, bootstrap likelihood -146015.476823, best rearrangement setting 5
Bootstrap[337]: Time 42.221392 seconds, bootstrap likelihood -144623.834445, best rearrangement setting 14
Bootstrap[421]: Time 45.821243 seconds, bootstrap likelihood -138637.762551, best rearrangement setting 15
Bootstrap[925]: Time 39.392860 seconds, bootstrap likelihood -137330.681614, best rearrangement setting 6
Bootstrap[1]: Time 44.806147 seconds, bootstrap likelihood -138074.328336, best rearrangement setting 13
Bootstrap[673]: Time 37.158805 seconds, bootstrap likelihood -135544.996876, best rearrangement setting 5
Bootstrap[253]: Time 45.646838 seconds, bootstrap likelihood -138098.393168, best rearrangement setting 14
Bootstrap[85]: Time 69.591492 seconds, bootstrap likelihood -138639.717450, best rearrangement setting 13
Bootstrap[170]: Time 39.151662 seconds, bootstrap likelihood -141792.872315, best rearrangement setting 14
Bootstrap[506]: Time 38.872789 seconds, bootstrap likelihood -142631.965274, best rearrangement setting 7
Bootstrap[590]: Time 39.061977 seconds, bootstrap likelihood -140161.412261, best rearrangement setting 8
Bootstrap[338]: Time 36.184199 seconds, bootstrap likelihood -139086.554258, best rearrangement setting 5
Bootstrap[842]: Time 42.474294 seconds, bootstrap likelihood -139676.387598, best rearrangement setting 11
Bootstrap[758]: Time 42.103999 seconds, bootstrap likelihood -139117.190473, best rearrangement setting 10
Bootstrap[422]: Time 40.141967 seconds, bootstrap likelihood -141447.235631, best rearrangement setting 6
Bootstrap[2]: Time 43.426601 seconds, bootstrap likelihood -138342.839630, best rearrangement setting 12
Bootstrap[674]: Time 42.108766 seconds, bootstrap likelihood -136017.340687, best rearrangement setting 9
Bootstrap[926]: Time 44.560332 seconds, bootstrap likelihood -139362.682246, best rearrangement setting 11
Bootstrap[254]: Time 45.388806 seconds, bootstrap likelihood -140613.431208, best rearrangement setting 15
Bootstrap[171]: Time 37.205122 seconds, bootstrap likelihood -141934.971949, best rearrangement setting 8
Bootstrap[591]: Time 36.361147 seconds, bootstrap likelihood -143174.628101, best rearrangement setting 6
Bootstrap[86]: Time 44.810783 seconds, bootstrap likelihood -137126.567634, best rearrangement setting 13
Bootstrap[339]: Time 43.114238 seconds, bootstrap likelihood -143937.410232, best rearrangement setting 11
Bootstrap[759]: Time 41.235367 seconds, bootstrap likelihood -142810.625613, best rearrangement setting 9
Bootstrap[507]: Time 46.994273 seconds, bootstrap likelihood -140347.919755, best rearrangement setting 15
Bootstrap[843]: Time 42.448634 seconds, bootstrap likelihood -143357.953601, best rearrangement setting 11
Bootstrap[423]: Time 42.536456 seconds, bootstrap likelihood -145629.405342, best rearrangement setting 13
Bootstrap[675]: Time 40.907029 seconds, bootstrap likelihood -135936.099600, best rearrangement setting 8
Bootstrap[3]: Time 44.603361 seconds, bootstrap likelihood -138538.321432, best rearrangement setting 15
Bootstrap[927]: Time 44.255491 seconds, bootstrap likelihood -138862.998120, best rearrangement setting 13
Bootstrap[255]: Time 42.039005 seconds, bootstrap likelihood -136430.300708, best rearrangement setting 10
Bootstrap[592]: Time 35.936686 seconds, bootstrap likelihood -143274.362732, best rearrangement setting 6
Bootstrap[172]: Time 40.397100 seconds, bootstrap likelihood -144229.071890, best rearrangement setting 14
Bootstrap[87]: Time 38.655791 seconds, bootstrap likelihood -137651.231600, best rearrangement setting 6
Bootstrap[340]: Time 37.690214 seconds, bootstrap likelihood -142106.812227, best rearrangement setting 6
Bootstrap[844]: Time 38.216936 seconds, bootstrap likelihood -143374.382814, best rearrangement setting 6
Bootstrap[508]: Time 40.114090 seconds, bootstrap likelihood -142028.208277, best rearrangement setting 10
Bootstrap[760]: Time 42.472854 seconds, bootstrap likelihood -140481.413728, best rearrangement setting 10
Bootstrap[424]: Time 44.730830 seconds, bootstrap likelihood -143033.884421, best rearrangement setting 14
Bootstrap[676]: Time 43.192039 seconds, bootstrap likelihood -138556.595961, best rearrangement setting 14
Bootstrap[4]: Time 42.247896 seconds, bootstrap likelihood -136114.700439, best rearrangement setting 10
Bootstrap[928]: Time 43.270837 seconds, bootstrap likelihood -140710.310434, best rearrangement setting 13
Bootstrap[256]: Time 43.237150 seconds, bootstrap likelihood -133927.457652, best rearrangement setting 10
Bootstrap[88]: Time 38.411358 seconds, bootstrap likelihood -136815.286556, best rearrangement setting 7
Bootstrap[425]: Time 36.563248 seconds, bootstrap likelihood -141760.681587, best rearrangement setting 5
Bootstrap[509]: Time 36.927379 seconds, bootstrap likelihood -142953.775565, best rearrangement setting 6
Bootstrap[593]: Time 39.661926 seconds, bootstrap likelihood -143365.457576, best rearrangement setting 7
Bootstrap[761]: Time 41.010483 seconds, bootstrap likelihood -140571.849343, best rearrangement setting 10
Bootstrap[173]: Time 41.412517 seconds, bootstrap likelihood -140550.203668, best rearrangement setting 12
Bootstrap[677]: Time 41.580178 seconds, bootstrap likelihood -136900.286313, best rearrangement setting 8
Bootstrap[845]: Time 42.435583 seconds, bootstrap likelihood -140533.232908, best rearrangement setting 11
Bootstrap[341]: Time 42.908797 seconds, bootstrap likelihood -142995.717056, best rearrangement setting 15
Bootstrap[5]: Time 43.085044 seconds, bootstrap likelihood -137709.579872, best rearrangement setting 10
Bootstrap[89]: Time 43.161288 seconds, bootstrap likelihood -137089.202622, best rearrangement setting 11
Bootstrap[929]: Time 43.493392 seconds, bootstrap likelihood -139183.345113, best rearrangement setting 12
Bootstrap[257]: Time 44.154905 seconds, bootstrap likelihood -138698.540096, best rearrangement setting 13
Bootstrap[426]: Time 35.363951 seconds, bootstrap likelihood -144062.988966, best rearrangement setting 5
Bootstrap[510]: Time 43.380251 seconds, bootstrap likelihood -141171.498369, best rearrangement setting 9
Bootstrap[594]: Time 40.820023 seconds, bootstrap likelihood -145903.665767, best rearrangement setting 13
Bootstrap[678]: Time 39.537520 seconds, bootstrap likelihood -137555.022183, best rearrangement setting 6
Bootstrap[6]: Time 38.994743 seconds, bootstrap likelihood -135168.451327, best rearrangement setting 6
Bootstrap[762]: Time 41.611026 seconds, bootstrap likelihood -142312.204933, best rearrangement setting 10
Bootstrap[174]: Time 41.796847 seconds, bootstrap likelihood -144608.273908, best rearrangement setting 14
Bootstrap[930]: Time 40.507067 seconds, bootstrap likelihood -136164.290090, best rearrangement setting 7
Bootstrap[258]: Time 40.193715 seconds, bootstrap likelihood -134656.730204, best rearrangement setting 7
Bootstrap[846]: Time 43.746337 seconds, bootstrap likelihood -139390.126651, best rearrangement setting 14
Bootstrap[90]: Time 43.692080 seconds, bootstrap likelihood -138556.924294, best rearrangement setting 10
Bootstrap[342]: Time 44.856287 seconds, bootstrap likelihood -141597.652645, best rearrangement setting 11
Bootstrap[427]: Time 43.929406 seconds, bootstrap likelihood -145738.518072, best rearrangement setting 11
Bootstrap[511]: Time 38.960639 seconds, bootstrap likelihood -138646.072255, best rearrangement setting 5
Bootstrap[595]: Time 40.734234 seconds, bootstrap likelihood -141341.510724, best rearrangement setting 11
Bootstrap[679]: Time 40.352595 seconds, bootstrap likelihood -138075.354289, best rearrangement setting 6
Bootstrap[763]: Time 42.444522 seconds, bootstrap likelihood -143183.518585, best rearrangement setting 12
Bootstrap[343]: Time 37.390585 seconds, bootstrap likelihood -141926.699968, best rearrangement setting 5
Bootstrap[7]: Time 43.294390 seconds, bootstrap likelihood -136192.697318, best rearrangement setting 14
Bootstrap[175]: Time 42.989595 seconds, bootstrap likelihood -142424.475399, best rearrangement setting 15
Bootstrap[259]: Time 42.568592 seconds, bootstrap likelihood -138825.683487, best rearrangement setting 10
Bootstrap[847]: Time 41.542508 seconds, bootstrap likelihood -142480.674145, best rearrangement setting 7
Bootstrap[91]: Time 42.133771 seconds, bootstrap likelihood -137960.637546, best rearrangement setting 9
Bootstrap[931]: Time 46.589318 seconds, bootstrap likelihood -136259.766241, best rearrangement setting 13
Bootstrap[428]: Time 42.458673 seconds, bootstrap likelihood -141220.732031, best rearrangement setting 14
Bootstrap[596]: Time 38.064509 seconds, bootstrap likelihood -140133.987730, best rearrangement setting 6
Bootstrap[8]: Time 37.424023 seconds, bootstrap likelihood -139172.937328, best rearrangement setting 5
Bootstrap[512]: Time 43.636525 seconds, bootstrap likelihood -142716.977502, best rearrangement setting 15
Bootstrap[680]: Time 41.412864 seconds, bootstrap likelihood -137879.484628, best rearrangement setting 8
Bootstrap[764]: Time 41.633233 seconds, bootstrap likelihood -143082.790696, best rearrangement setting 9
Bootstrap[176]: Time 41.014875 seconds, bootstrap likelihood -142092.085556, best rearrangement setting 9
Bootstrap[344]: Time 42.387612 seconds, bootstrap likelihood -143341.897455, best rearrangement setting 12
Bootstrap[92]: Time 39.928413 seconds, bootstrap likelihood -136975.686343, best rearrangement setting 7
Bootstrap[260]: Time 43.779034 seconds, bootstrap likelihood -136123.622916, best rearrangement setting 10
Bootstrap[848]: Time 43.736082 seconds, bootstrap likelihood -142897.406812, best rearrangement setting 11
Bootstrap[932]: Time 45.625900 seconds, bootstrap likelihood -138465.900068, best rearrangement setting 13
Bootstrap[681]: Time 37.312654 seconds, bootstrap likelihood -138161.175879, best rearrangement setting 5
Bootstrap[177]: Time 37.358844 seconds, bootstrap likelihood -139182.142586, best rearrangement setting 6
Bootstrap[849]: Time 37.754518 seconds, bootstrap likelihood -138711.434378, best rearrangement setting 5
Bootstrap[345]: Time 39.464431 seconds, bootstrap likelihood -143358.717534, best rearrangement setting 6
Bootstrap[513]: Time 39.714495 seconds, bootstrap likelihood -141121.969432, best rearrangement setting 6
Bootstrap[597]: Time 40.187493 seconds, bootstrap likelihood -141322.582746, best rearrangement setting 11
Bootstrap[9]: Time 40.540658 seconds, bootstrap likelihood -134616.055095, best rearrangement setting 7
Bootstrap[765]: Time 41.715709 seconds, bootstrap likelihood -141199.082568, best rearrangement setting 11
Bootstrap[933]: Time 42.839475 seconds, bootstrap likelihood -138226.270726, best rearrangement setting 10
Bootstrap[261]: Time 42.847216 seconds, bootstrap likelihood -138113.667473, best rearrangement setting 12
Bootstrap[429]: Time 42.993365 seconds, bootstrap likelihood -139105.932898, best rearrangement setting 11
Bootstrap[93]: Time 43.612511 seconds, bootstrap likelihood -141722.989708, best rearrangement setting 12
Bootstrap[598]: Time 47.059600 seconds, bootstrap likelihood -141347.031841, best rearrangement setting 5
Bootstrap[682]: Time 53.423652 seconds, bootstrap likelihood -138956.625798, best rearrangement setting 8
Bootstrap[10]: Time 52.682051 seconds, bootstrap likelihood -138081.815215, best rearrangement setting 7
Bootstrap[178]: Time 58.282299 seconds, bootstrap likelihood -143297.486621, best rearrangement setting 13
Bootstrap[514]: Time 56.301489 seconds, bootstrap likelihood -142551.470337, best rearrangement setting 13
Bootstrap[262]: Time 53.251968 seconds, bootstrap likelihood -137350.379723, best rearrangement setting 5
Bootstrap[346]: Time 56.713123 seconds, bootstrap likelihood -137783.636522, best rearrangement setting 7
Bootstrap[934]: Time 53.729028 seconds, bootstrap likelihood -140032.128682, best rearrangement setting 5
Bootstrap[766]: Time 55.592425 seconds, bootstrap likelihood -142568.237224, best rearrangement setting 11
Bootstrap[430]: Time 58.271685 seconds, bootstrap likelihood -143849.574693, best rearrangement setting 10
Bootstrap[850]: Time 63.796067 seconds, bootstrap likelihood -141427.687171, best rearrangement setting 13
Bootstrap[94]: Time 58.150868 seconds, bootstrap likelihood -135794.221819, best rearrangement setting 10
Bootstrap[599]: Time 42.575927 seconds, bootstrap likelihood -143388.229290, best rearrangement setting 14
Bootstrap[11]: Time 37.589510 seconds, bootstrap likelihood -138874.950900, best rearrangement setting 5
Bootstrap[767]: Time 38.329343 seconds, bootstrap likelihood -142754.183197, best rearrangement setting 6
Bootstrap[683]: Time 44.991031 seconds, bootstrap likelihood -135682.788511, best rearrangement setting 15
Bootstrap[179]: Time 40.126345 seconds, bootstrap likelihood -142014.886434, best rearrangement setting 7
Bootstrap[263]: Time 42.432687 seconds, bootstrap likelihood -137545.427650, best rearrangement setting 9
Bootstrap[935]: Time 43.205949 seconds, bootstrap likelihood -136608.329772, best rearrangement setting 8
Bootstrap[347]: Time 43.635387 seconds, bootstrap likelihood -142894.129484, best rearrangement setting 10
Bootstrap[515]: Time 44.130775 seconds, bootstrap likelihood -142524.796856, best rearrangement setting 13
Bootstrap[95]: Time 39.600154 seconds, bootstrap likelihood -139438.418928, best rearrangement setting 6
Bootstrap[851]: Time 40.382016 seconds, bootstrap likelihood -143566.113069, best rearrangement setting 7
Bootstrap[431]: Time 41.972651 seconds, bootstrap likelihood -141324.801514, best rearrangement setting 11
Bootstrap[12]: Time 41.786929 seconds, bootstrap likelihood -138606.962530, best rearrangement setting 8
Bootstrap[600]: Time 42.843391 seconds, bootstrap likelihood -140426.367223, best rearrangement setting 12
Bootstrap[684]: Time 40.044535 seconds, bootstrap likelihood -135480.972121, best rearrangement setting 7
Bootstrap[180]: Time 40.670153 seconds, bootstrap likelihood -144553.466186, best rearrangement setting 11
Bootstrap[516]: Time 37.054601 seconds, bootstrap likelihood -141017.293046, best rearrangement setting 5
Bootstrap[768]: Time 42.103308 seconds, bootstrap likelihood -138556.966846, best rearrangement setting 14
Bootstrap[936]: Time 38.238140 seconds, bootstrap likelihood -140170.957357, best rearrangement setting 5
Bootstrap[264]: Time 40.452307 seconds, bootstrap likelihood -138610.559690, best rearrangement setting 7
Bootstrap[432]: Time 40.114984 seconds, bootstrap likelihood -143170.374154, best rearrangement setting 9
Bootstrap[348]: Time 44.282943 seconds, bootstrap likelihood -145290.475816, best rearrangement setting 13
Bootstrap[852]: Time 43.225930 seconds, bootstrap likelihood -142315.727708, best rearrangement setting 10
Bootstrap[96]: Time 44.780381 seconds, bootstrap likelihood -133446.107675, best rearrangement setting 15
Bootstrap[433]: Time 36.802867 seconds, bootstrap likelihood -141354.925129, best rearrangement setting 5
Bootstrap[601]: Time 39.655853 seconds, bootstrap likelihood -140403.658098, best rearrangement setting 9
Bootstrap[517]: Time 39.757576 seconds, bootstrap likelihood -143105.165664, best rearrangement setting 7
Bootstrap[181]: Time 40.434880 seconds, bootstrap likelihood -139768.630414, best rearrangement setting 10
Bootstrap[13]: Time 40.610240 seconds, bootstrap likelihood -138854.849322, best rearrangement setting 7
Bootstrap[937]: Time 40.884353 seconds, bootstrap likelihood -139545.002761, best rearrangement setting 6
Bootstrap[97]: Time 42.265985 seconds, bootstrap likelihood -136320.061826, best rearrangement setting 9
Bootstrap[769]: Time 42.528828 seconds, bootstrap likelihood -141636.680948, best rearrangement setting 13
Bootstrap[349]: Time 43.183383 seconds, bootstrap likelihood -138696.409106, best rearrangement setting 14
Bootstrap[853]: Time 43.905167 seconds, bootstrap likelihood -142207.883948, best rearrangement setting 15
Bootstrap[685]: Time 44.697526 seconds, bootstrap likelihood -138928.056217, best rearrangement setting 11
Bootstrap[265]: Time 44.829881 seconds, bootstrap likelihood -135001.796781, best rearrangement setting 12
Bootstrap[434]: Time 35.974350 seconds, bootstrap likelihood -143665.490810, best rearrangement setting 5
Bootstrap[182]: Time 38.258086 seconds, bootstrap likelihood -138416.073241, best rearrangement setting 7
Bootstrap[518]: Time 39.359694 seconds, bootstrap likelihood -142730.962178, best rearrangement setting 8
Bootstrap[770]: Time 37.998217 seconds, bootstrap likelihood -139530.549203, best rearrangement setting 6
Bootstrap[602]: Time 41.911987 seconds, bootstrap likelihood -140718.864688, best rearrangement setting 11
Bootstrap[854]: Time 39.888078 seconds, bootstrap likelihood -140961.543412, best rearrangement setting 8
Bootstrap[14]: Time 44.914577 seconds, bootstrap likelihood -138796.984310, best rearrangement setting 12
Bootstrap[350]: Time 42.926400 seconds, bootstrap likelihood -143428.393449, best rearrangement setting 13
Bootstrap[266]: Time 41.423506 seconds, bootstrap likelihood -137670.845256, best rearrangement setting 10
Bootstrap[938]: Time 45.503665 seconds, bootstrap likelihood -141353.554550, best rearrangement setting 11
Bootstrap[98]: Time 44.255421 seconds, bootstrap likelihood -135984.827589, best rearrangement setting 15
Bootstrap[686]: Time 44.579610 seconds, bootstrap likelihood -138978.895705, best rearrangement setting 14
Bootstrap[435]: Time 43.649652 seconds, bootstrap likelihood -144789.097087, best rearrangement setting 12
Bootstrap[183]: Time 39.893690 seconds, bootstrap likelihood -142204.406170, best rearrangement setting 14
Bootstrap[771]: Time 39.695385 seconds, bootstrap likelihood -142157.917847, best rearrangement setting 10
Bootstrap[603]: Time 40.724695 seconds, bootstrap likelihood -143569.302910, best rearrangement setting 11
Bootstrap[519]: Time 44.792305 seconds, bootstrap likelihood -139974.862832, best rearrangement setting 12
Bootstrap[855]: Time 42.313297 seconds, bootstrap likelihood -141692.725121, best rearrangement setting 10
Bootstrap[351]: Time 43.162719 seconds, bootstrap likelihood -142655.150310, best rearrangement setting 13
Bootstrap[99]: Time 43.299532 seconds, bootstrap likelihood -136720.460045, best rearrangement setting 14
Bootstrap[939]: Time 43.433256 seconds, bootstrap likelihood -135495.644280, best rearrangement setting 9
Bootstrap[15]: Time 44.955553 seconds, bootstrap likelihood -139125.821128, best rearrangement setting 15
Bootstrap[267]: Time 44.316224 seconds, bootstrap likelihood -139214.984092, best rearrangement setting 13
Bootstrap[687]: Time 43.711326 seconds, bootstrap likelihood -138857.988351, best rearrangement setting 11
Bootstrap[436]: Time 41.406055 seconds, bootstrap likelihood -139446.824916, best rearrangement setting 9
Bootstrap[184]: Time 41.925533 seconds, bootstrap likelihood -140975.379128, best rearrangement setting 13
Bootstrap[772]: Time 41.938333 seconds, bootstrap likelihood -142425.663054, best rearrangement setting 11
Bootstrap[604]: Time 40.818807 seconds, bootstrap likelihood -145126.155549, best rearrangement setting 10
Bootstrap[856]: Time 39.121733 seconds, bootstrap likelihood -142046.710936, best rearrangement setting 6
Bootstrap[520]: Time 43.257887 seconds, bootstrap likelihood -144896.490085, best rearrangement setting 15
Bootstrap[688]: Time 37.300637 seconds, bootstrap likelihood -138821.394477, best rearrangement setting 5
Bootstrap[352]: Time 41.033843 seconds, bootstrap likelihood -144156.458494, best rearrangement setting 14
Bootstrap[100]: Time 41.335215 seconds, bootstrap likelihood -135855.253123, best rearrangement setting 7
Bootstrap[268]: Time 40.766431 seconds, bootstrap likelihood -136949.061651, best rearrangement setting 8
Bootstrap[16]: Time 43.290615 seconds, bootstrap likelihood -138128.265316, best rearrangement setting 12
Bootstrap[940]: Time 45.769446 seconds, bootstrap likelihood -141010.272797, best rearrangement setting 12
Bootstrap[185]: Time 41.177824 seconds, bootstrap likelihood -142032.768678, best rearrangement setting 12
Bootstrap[353]: Time 41.607123 seconds, bootstrap likelihood -140921.801780, best rearrangement setting 12
Bootstrap[605]: Time 41.997919 seconds, bootstrap likelihood -144235.399398, best rearrangement setting 12
Bootstrap[437]: Time 43.222553 seconds, bootstrap likelihood -140501.892389, best rearrangement setting 12
Bootstrap[269]: Time 43.486036 seconds, bootstrap likelihood -140854.885073, best rearrangement setting 12
Bootstrap[521]: Time 43.515297 seconds, bootstrap likelihood -141715.068969, best rearrangement setting 12
Bootstrap[773]: Time 43.612912 seconds, bootstrap likelihood -140492.496991, best rearrangement setting 12
Bootstrap[689]: Time 43.700988 seconds, bootstrap likelihood -137589.849921, best rearrangement setting 12
Bootstrap[857]: Time 43.942619 seconds, bootstrap likelihood -144045.055058, best rearrangement setting 12
Bootstrap[101]: Time 44.200900 seconds, bootstrap likelihood -138953.665348, best rearrangement setting 12
Bootstrap[17]: Time 44.710078 seconds, bootstrap likelihood -135182.487818, best rearrangement setting 12
Bootstrap[941]: Time 44.825470 seconds, bootstrap likelihood -140970.143544, best rearrangement setting 12
Bootstrap[522]: Time 36.751059 seconds, bootstrap likelihood -139716.878527, best rearrangement setting 5
Bootstrap[18]: Time 37.225271 seconds, bootstrap likelihood -139224.514528, best rearrangement setting 5
Bootstrap[186]: Time 41.172651 seconds, bootstrap likelihood -143115.785460, best rearrangement setting 12
Bootstrap[354]: Time 40.884521 seconds, bootstrap likelihood -142698.181185, best rearrangement setting 9
Bootstrap[438]: Time 40.943442 seconds, bootstrap likelihood -141406.640217, best rearrangement setting 7
Bootstrap[858]: Time 41.625013 seconds, bootstrap likelihood -142835.674821, best rearrangement setting 9
Bootstrap[606]: Time 43.866824 seconds, bootstrap likelihood -139067.977312, best rearrangement setting 15
Bootstrap[270]: Time 42.640909 seconds, bootstrap likelihood -137346.424930, best rearrangement setting 11
Bootstrap[774]: Time 42.429993 seconds, bootstrap likelihood -140511.575871, best rearrangement setting 11
Bootstrap[690]: Time 42.989532 seconds, bootstrap likelihood -135523.101310, best rearrangement setting 13
Bootstrap[942]: Time 43.792456 seconds, bootstrap likelihood -137431.732136, best rearrangement setting 8
Bootstrap[102]: Time 44.582655 seconds, bootstrap likelihood -138393.815336, best rearrangement setting 14
Bootstrap[523]: Time 39.235881 seconds, bootstrap likelihood -140464.756729, best rearrangement setting 6
Bootstrap[187]: Time 41.122091 seconds, bootstrap likelihood -141293.895561, best rearrangement setting 15
Bootstrap[19]: Time 42.366786 seconds, bootstrap likelihood -139732.584732, best rearrangement setting 8
Bootstrap[439]: Time 40.719908 seconds, bootstrap likelihood -141768.614724, best rearrangement setting 8
Bootstrap[355]: Time 42.764478 seconds, bootstrap likelihood -139640.492893, best rearrangement setting 10
Bootstrap[859]: Time 40.017221 seconds, bootstrap likelihood -140059.437049, best rearrangement setting 9
Bootstrap[607]: Time 41.513817 seconds, bootstrap likelihood -141516.137756, best rearrangement setting 15
Bootstrap[103]: Time 39.032529 seconds, bootstrap likelihood -138564.244123, best rearrangement setting 6
Bootstrap[271]: Time 42.125147 seconds, bootstrap likelihood -139066.992111, best rearrangement setting 13
Bootstrap[775]: Time 42.396167 seconds, bootstrap likelihood -140851.744857, best rearrangement setting 11
Bootstrap[943]: Time 41.591087 seconds, bootstrap likelihood -138970.062365, best rearrangement setting 7
Bootstrap[691]: Time 44.289107 seconds, bootstrap likelihood -138143.852981, best rearrangement setting 13
Bootstrap[188]: Time 50.760176 seconds, bootstrap likelihood -145001.730236, best rearrangement setting 7
Bootstrap[272]: Time 49.755806 seconds, bootstrap likelihood -137471.132458, best rearrangement setting 5
Bootstrap[860]: Time 52.799450 seconds, bootstrap likelihood -143006.856681, best rearrangement setting 6
Bootstrap[20]: Time 54.897040 seconds, bootstrap likelihood -139064.540800, best rearrangement setting 10
Bootstrap[524]: Time 59.904196 seconds, bootstrap likelihood -138445.737838, best rearrangement setting 12
Bootstrap[356]: Time 55.584252 seconds, bootstrap likelihood -142318.454692, best rearrangement setting 15
Bootstrap[440]: Time 58.005399 seconds, bootstrap likelihood -139996.136512, best rearrangement setting 13
Bootstrap[104]: Time 55.198292 seconds, bootstrap likelihood -138058.629784, best rearrangement setting 8
Bootstrap[944]: Time 52.859808 seconds, bootstrap likelihood -139761.803879, best rearrangement setting 5
Bootstrap[776]: Time 55.457154 seconds, bootstrap likelihood -139147.581969, best rearrangement setting 8
Bootstrap[608]: Time 57.420299 seconds, bootstrap likelihood -144471.195722, best rearrangement setting 11
Bootstrap[692]: Time 55.455635 seconds, bootstrap likelihood -140258.637110, best rearrangement setting 9
Bootstrap[609]: Time 37.433384 seconds, bootstrap likelihood -140359.077291, best rearrangement setting 6
Bootstrap[861]: Time 37.750569 seconds, bootstrap likelihood -140631.009686, best rearrangement setting 5
Bootstrap[21]: Time 39.050560 seconds, bootstrap likelihood -139297.940042, best rearrangement setting 6
Bootstrap[357]: Time 39.919724 seconds, bootstrap likelihood -142232.109487, best rearrangement setting 8
Bootstrap[189]: Time 41.016008 seconds, bootstrap likelihood -143271.247571, best rearrangement setting 12
Bootstrap[105]: Time 41.345726 seconds, bootstrap likelihood -137438.525418, best rearrangement setting 9
Bootstrap[441]: Time 42.086842 seconds, bootstrap likelihood -141466.096608, best rearrangement setting 11
Bootstrap[777]: Time 42.448139 seconds, bootstrap likelihood -142562.767917, best rearrangement setting 12
Bootstrap[945]: Time 43.464112 seconds, bootstrap likelihood -139239.102289, best rearrangement setting 8
Bootstrap[693]: Time 43.564002 seconds, bootstrap likelihood -139496.070952, best rearrangement setting 9
Bootstrap[525]: Time 44.912795 seconds, bootstrap likelihood -143183.621473, best rearrangement setting 14
Bootstrap[273]: Time 45.928721 seconds, bootstrap likelihood -136755.844057, best rearrangement setting 15
Bootstrap[610]: Time 39.119610 seconds, bootstrap likelihood -139766.604342, best rearrangement setting 8
Bootstrap[22]: Time 37.857817 seconds, bootstrap likelihood -139913.126761, best rearrangement setting 5
Bootstrap[862]: Time 41.511083 seconds, bootstrap likelihood -141489.643197, best rearrangement setting 8
Bootstrap[190]: Time 40.053609 seconds, bootstrap likelihood -141681.443399, best rearrangement setting 12
Bootstrap[358]: Time 42.842890 seconds, bootstrap likelihood -139381.856648, best rearrangement setting 8
Bootstrap[274]: Time 37.916227 seconds, bootstrap likelihood -138970.410236, best rearrangement setting 5
Bootstrap[106]: Time 42.784746 seconds, bootstrap likelihood -139094.534320, best rearrangement setting 8
Bootstrap[778]: Time 41.788778 seconds, bootstrap likelihood -141694.696925, best rearrangement setting 15
Bootstrap[442]: Time 43.972110 seconds, bootstrap likelihood -142507.179922, best rearrangement setting 12
Bootstrap[694]: Time 44.972828 seconds, bootstrap likelihood -137985.514445, best rearrangement setting 12
Bootstrap[946]: Time 45.419077 seconds, bootstrap likelihood -135184.555781, best rearrangement setting 11
Bootstrap[526]: Time 44.750770 seconds, bootstrap likelihood -143751.896507, best rearrangement setting 15
Bootstrap[23]: Time 40.622007 seconds, bootstrap likelihood -138513.904387, best rearrangement setting 7
Bootstrap[863]: Time 40.987430 seconds, bootstrap likelihood -141106.986853, best rearrangement setting 7
Bootstrap[611]: Time 44.439328 seconds, bootstrap likelihood -142494.762889, best rearrangement setting 15
Bootstrap[191]: Time 40.022292 seconds, bootstrap likelihood -142036.170323, best rearrangement setting 9
Bootstrap[359]: Time 41.243214 seconds, bootstrap likelihood -140934.276574, best rearrangement setting 11
Bootstrap[779]: Time 39.871110 seconds, bootstrap likelihood -142717.564292, best rearrangement setting 6
Bootstrap[107]: Time 41.619821 seconds, bootstrap likelihood -135719.961029, best rearrangement setting 8
Bootstrap[695]: Time 37.499267 seconds, bootstrap likelihood -132868.485578, best rearrangement setting 5
Bootstrap[275]: Time 43.347717 seconds, bootstrap likelihood -141301.749413, best rearrangement setting 10
Bootstrap[443]: Time 43.500213 seconds, bootstrap likelihood -143107.319152, best rearrangement setting 12
Bootstrap[947]: Time 42.581668 seconds, bootstrap likelihood -140248.083890, best rearrangement setting 8
Bootstrap[527]: Time 44.117485 seconds, bootstrap likelihood -140015.332903, best rearrangement setting 13
Bootstrap[864]: Time 37.438062 seconds, bootstrap likelihood -141606.700707, best rearrangement setting 5
Bootstrap[24]: Time 40.575507 seconds, bootstrap likelihood -135763.635141, best rearrangement setting 8
Bootstrap[192]: Time 38.009989 seconds, bootstrap likelihood -142185.168792, best rearrangement setting 7
Bootstrap[612]: Time 38.418109 seconds, bootstrap likelihood -143702.396785, best rearrangement setting 6
Bootstrap[780]: Time 37.392692 seconds, bootstrap likelihood -139349.949095, best rearrangement setting 5
Bootstrap[360]: Time 40.145345 seconds, bootstrap likelihood -140153.737488, best rearrangement setting 7
Bootstrap[696]: Time 38.718282 seconds, bootstrap likelihood -136563.206733, best rearrangement setting 6
Bootstrap[108]: Time 41.333412 seconds, bootstrap likelihood -136362.788549, best rearrangement setting 7
Bootstrap[444]: Time 38.300438 seconds, bootstrap likelihood -141888.005339, best rearrangement setting 6
Bootstrap[276]: Time 41.105505 seconds, bootstrap likelihood -138179.083632, best rearrangement setting 7
Bootstrap[948]: Time 38.032165 seconds, bootstrap likelihood -139845.741784, best rearrangement setting 5
Bootstrap[528]: Time 38.781390 seconds, bootstrap likelihood -141369.642812, best rearrangement setting 6
Bootstrap[697]: Time 37.536124 seconds, bootstrap likelihood -134778.760559, best rearrangement setting 5
Bootstrap[193]: Time 38.860074 seconds, bootstrap likelihood -138755.592185, best rearrangement setting 9
Bootstrap[781]: Time 39.878584 seconds, bootstrap likelihood -142830.614238, best rearrangement setting 6
Bootstrap[25]: Time 40.085859 seconds, bootstrap likelihood -136596.140334, best rearrangement setting 6
Bootstrap[109]: Time 41.148488 seconds, bootstrap likelihood -140519.743947, best rearrangement setting 7
Bootstrap[361]: Time 41.514005 seconds, bootstrap likelihood -140498.175072, best rearrangement setting 11
Bootstrap[865]: Time 41.527442 seconds, bootstrap likelihood -139874.616072, best rearrangement setting 7
Bootstrap[445]: Time 41.673198 seconds, bootstrap likelihood -142874.476762, best rearrangement setting 12
Bootstrap[277]: Time 42.092169 seconds, bootstrap likelihood -141421.771838, best rearrangement setting 10
Bootstrap[949]: Time 43.405008 seconds, bootstrap likelihood -137047.878629, best rearrangement setting 9
Bootstrap[613]: Time 44.367838 seconds, bootstrap likelihood -139089.008185, best rearrangement setting 15
Bootstrap[529]: Time 45.544765 seconds, bootstrap likelihood -141588.729367, best rearrangement setting 14
Bootstrap[194]: Time 37.816827 seconds, bootstrap likelihood -141787.887585, best rearrangement setting 7
Bootstrap[446]: Time 37.070313 seconds, bootstrap likelihood -139474.124565, best rearrangement setting 5
Bootstrap[782]: Time 39.495256 seconds, bootstrap likelihood -139120.614651, best rearrangement setting 6
Bootstrap[698]: Time 44.573958 seconds, bootstrap likelihood -139050.473357, best rearrangement setting 14
Bootstrap[26]: Time 43.801213 seconds, bootstrap likelihood -137650.473126, best rearrangement setting 12
Bootstrap[362]: Time 42.950397 seconds, bootstrap likelihood -144153.451110, best rearrangement setting 13
Bootstrap[278]: Time 42.544103 seconds, bootstrap likelihood -136556.519023, best rearrangement setting 10
Bootstrap[110]: Time 43.722754 seconds, bootstrap likelihood -138486.488778, best rearrangement setting 15
Bootstrap[866]: Time 44.062411 seconds, bootstrap likelihood -142595.154683, best rearrangement setting 9
Bootstrap[614]: Time 42.131779 seconds, bootstrap likelihood -142265.145528, best rearrangement setting 11
Bootstrap[950]: Time 43.295863 seconds, bootstrap likelihood -138148.488001, best rearrangement setting 12
Bootstrap[530]: Time 42.280018 seconds, bootstrap likelihood -142640.277373, best rearrangement setting 8
Bootstrap[195]: Time 35.269739 seconds, bootstrap likelihood -139125.484075, best rearrangement setting 5
Bootstrap[783]: Time 39.309057 seconds, bootstrap likelihood -139735.601699, best rearrangement setting 8
Bootstrap[447]: Time 42.033013 seconds, bootstrap likelihood -140408.833279, best rearrangement setting 8
Bootstrap[867]: Time 38.017665 seconds, bootstrap likelihood -141851.829630, best rearrangement setting 5
Bootstrap[531]: Time 36.931516 seconds, bootstrap likelihood -144297.838551, best rearrangement setting 5
Bootstrap[699]: Time 43.925368 seconds, bootstrap likelihood -141873.358979, best rearrangement setting 11
Bootstrap[111]: Time 41.248791 seconds, bootstrap likelihood -138521.994465, best rearrangement setting 8
Bootstrap[363]: Time 41.878462 seconds, bootstrap likelihood -143956.717916, best rearrangement setting 11
Bootstrap[279]: Time 42.614377 seconds, bootstrap likelihood -137553.590002, best rearrangement setting 13
Bootstrap[27]: Time 44.405758 seconds, bootstrap likelihood -133850.837968, best rearrangement setting 10
Bootstrap[615]: Time 42.735691 seconds, bootstrap likelihood -139491.904955, best rearrangement setting 13
Bootstrap[951]: Time 46.529431 seconds, bootstrap likelihood -140159.637178, best rearrangement setting 13
Bootstrap[196]: Time 41.797030 seconds, bootstrap likelihood -142266.341047, best rearrangement setting 12
Bootstrap[784]: Time 41.307162 seconds, bootstrap likelihood -146201.349158, best rearrangement setting 9
Bootstrap[448]: Time 40.259889 seconds, bootstrap likelihood -141783.914956, best rearrangement setting 8
Bootstrap[112]: Time 39.484476 seconds, bootstrap likelihood -135813.554792, best rearrangement setting 6
Bootstrap[364]: Time 41.417426 seconds, bootstrap likelihood -143325.080393, best rearrangement setting 13
Bootstrap[532]: Time 43.735116 seconds, bootstrap likelihood -141110.783694, best rearrangement setting 13
Bootstrap[700]: Time 42.934117 seconds, bootstrap likelihood -140040.384290, best rearrangement setting 14
Bootstrap[280]: Time 41.811549 seconds, bootstrap likelihood -138164.294112, best rearrangement setting 7
Bootstrap[616]: Time 39.972378 seconds, bootstrap likelihood -137890.360028, best rearrangement setting 8
Bootstrap[868]: Time 47.200008 seconds, bootstrap likelihood -143049.222985, best rearrangement setting 15
Bootstrap[28]: Time 44.582067 seconds, bootstrap likelihood -138794.715784, best rearrangement setting 11
Bootstrap[952]: Time 42.523237 seconds, bootstrap likelihood -138918.159818, best rearrangement setting 10
Bootstrap[197]: Time 41.059132 seconds, bootstrap likelihood -140985.283198, best rearrangement setting 15
Bootstrap[449]: Time 40.680526 seconds, bootstrap likelihood -140671.905692, best rearrangement setting 8
Bootstrap[785]: Time 41.739013 seconds, bootstrap likelihood -138777.011503, best rearrangement setting 13
Bootstrap[281]: Time 36.549803 seconds, bootstrap likelihood -137563.266143, best rearrangement setting 5
Bootstrap[617]: Time 38.670576 seconds, bootstrap likelihood -139566.015057, best rearrangement setting 11
Bootstrap[365]: Time 40.378099 seconds, bootstrap likelihood -143063.889968, best rearrangement setting 7
Bootstrap[533]: Time 40.929768 seconds, bootstrap likelihood -142126.490855, best rearrangement setting 9
Bootstrap[113]: Time 44.382150 seconds, bootstrap likelihood -137950.510579, best rearrangement setting 14
Bootstrap[701]: Time 42.623406 seconds, bootstrap likelihood -138188.902538, best rearrangement setting 12
Bootstrap[953]: Time 37.396175 seconds, bootstrap likelihood -140204.738960, best rearrangement setting 5
Bootstrap[869]: Time 43.397654 seconds, bootstrap likelihood -141102.528446, best rearrangement setting 15
Bootstrap[29]: Time 42.122831 seconds, bootstrap likelihood -137416.268688, best rearrangement setting 12
Bootstrap[198]: Time 47.381625 seconds, bootstrap likelihood -139503.079866, best rearrangement setting 5
Bootstrap[450]: Time 48.364834 seconds, bootstrap likelihood -139377.317398, best rearrangement setting 6
Bootstrap[282]: Time 48.734306 seconds, bootstrap likelihood -135646.829807, best rearrangement setting 5
Bootstrap[114]: Time 49.274692 seconds, bootstrap likelihood -138817.869007, best rearrangement setting 5
Bootstrap[786]: Time 51.881860 seconds, bootstrap likelihood -139834.947679, best rearrangement setting 8
Bootstrap[702]: Time 52.106460 seconds, bootstrap likelihood -141179.337642, best rearrangement setting 7
Bootstrap[618]: Time 52.527447 seconds, bootstrap likelihood -143108.904439, best rearrangement setting 7
Bootstrap[366]: Time 54.435617 seconds, bootstrap likelihood -142718.413279, best rearrangement setting 6
Bootstrap[870]: Time 55.191814 seconds, bootstrap likelihood -143478.935506, best rearrangement setting 8
Bootstrap[534]: Time 56.190335 seconds, bootstrap likelihood -142899.380679, best rearrangement setting 7
Bootstrap[954]: Time 59.746836 seconds, bootstrap likelihood -134134.637369, best rearrangement setting 9
Bootstrap[30]: Time 60.012478 seconds, bootstrap likelihood -136164.364314, best rearrangement setting 15
Bootstrap[451]: Time 38.194999 seconds, bootstrap likelihood -143382.030422, best rearrangement setting 6
Bootstrap[199]: Time 39.282152 seconds, bootstrap likelihood -141402.911246, best rearrangement setting 9
Bootstrap[115]: Time 40.421045 seconds, bootstrap likelihood -139206.244560, best rearrangement setting 7
Bootstrap[283]: Time 43.621035 seconds, bootstrap likelihood -137204.732865, best rearrangement setting 12
Bootstrap[619]: Time 40.863767 seconds, bootstrap likelihood -144470.585190, best rearrangement setting 11
Bootstrap[787]: Time 42.192162 seconds, bootstrap likelihood -142355.078800, best rearrangement setting 15
Bootstrap[871]: Time 40.854158 seconds, bootstrap likelihood -143759.733535, best rearrangement setting 7
Bootstrap[535]: Time 40.653030 seconds, bootstrap likelihood -142302.327856, best rearrangement setting 8
Bootstrap[703]: Time 45.075354 seconds, bootstrap likelihood -141018.927407, best rearrangement setting 13
Bootstrap[367]: Time 43.679449 seconds, bootstrap likelihood -139788.966706, best rearrangement setting 14
Bootstrap[955]: Time 42.580531 seconds, bootstrap likelihood -134283.689324, best rearrangement setting 9
Bootstrap[31]: Time 44.460101 seconds, bootstrap likelihood -138564.880749, best rearrangement setting 15
Bootstrap[200]: Time 39.334527 seconds, bootstrap likelihood -145170.063263, best rearrangement setting 8
Bootstrap[116]: Time 39.310826 seconds, bootstrap likelihood -135318.468652, best rearrangement setting 7
Bootstrap[452]: Time 43.161949 seconds, bootstrap likelihood -141797.225107, best rearrangement setting 12
Bootstrap[788]: Time 39.963799 seconds, bootstrap likelihood -141119.859222, best rearrangement setting 7
Bootstrap[620]: Time 40.814555 seconds, bootstrap likelihood -142112.959347, best rearrangement setting 15
Bootstrap[704]: Time 37.697795 seconds, bootstrap likelihood -136596.405030, best rearrangement setting 5
Bootstrap[284]: Time 43.949538 seconds, bootstrap likelihood -137315.217455, best rearrangement setting 10
Bootstrap[872]: Time 43.410015 seconds, bootstrap likelihood -143784.327962, best rearrangement setting 8
Bootstrap[368]: Time 42.089088 seconds, bootstrap likelihood -141554.056598, best rearrangement setting 11
Bootstrap[536]: Time 43.857772 seconds, bootstrap likelihood -143122.935332, best rearrangement setting 14
Bootstrap[32]: Time 39.113349 seconds, bootstrap likelihood -136536.899269, best rearrangement setting 6
Bootstrap[956]: Time 44.690230 seconds, bootstrap likelihood -138094.234852, best rearrangement setting 10
Bootstrap[201]: Time 41.808171 seconds, bootstrap likelihood -142013.720600, best rearrangement setting 13
Bootstrap[453]: Time 42.029855 seconds, bootstrap likelihood -142102.121056, best rearrangement setting 10
Bootstrap[789]: Time 39.295882 seconds, bootstrap likelihood -141679.372917, best rearrangement setting 7
Bootstrap[117]: Time 45.023749 seconds, bootstrap likelihood -134678.902096, best rearrangement setting 14
Bootstrap[621]: Time 40.317284 seconds, bootstrap likelihood -140620.736589, best rearrangement setting 9
Bootstrap[705]: Time 42.606519 seconds, bootstrap likelihood -136350.605206, best rearrangement setting 8
Bootstrap[873]: Time 38.789017 seconds, bootstrap likelihood -139639.711376, best rearrangement setting 6
Bootstrap[285]: Time 43.503502 seconds, bootstrap likelihood -135575.609260, best rearrangement setting 12
Bootstrap[369]: Time 39.714451 seconds, bootstrap likelihood -144386.798349, best rearrangement setting 11
Bootstrap[537]: Time 44.085604 seconds, bootstrap likelihood -141084.336504, best rearrangement setting 10
Bootstrap[957]: Time 37.873065 seconds, bootstrap likelihood -139813.154124, best rearrangement setting 5
Bootstrap[33]: Time 44.148309 seconds, bootstrap likelihood -139170.262547, best rearrangement setting 15
Bootstrap[202]: Time 34.971391 seconds, bootstrap likelihood -141353.894482, best rearrangement setting 5
Bootstrap[538]: Time 36.788146 seconds, bootstrap likelihood -142778.368639, best rearrangement setting 5
Bootstrap[454]: Time 39.319884 seconds, bootstrap likelihood -140197.719660, best rearrangement setting 8
Bootstrap[790]: Time 40.102494 seconds, bootstrap likelihood -141577.235451, best rearrangement setting 7
Bootstrap[118]: Time 41.449823 seconds, bootstrap likelihood -138611.572119, best rearrangement setting 8
Bootstrap[622]: Time 41.481718 seconds, bootstrap likelihood -141363.465388, best rearrangement setting 13
Bootstrap[706]: Time 42.940004 seconds, bootstrap likelihood -138364.601252, best rearrangement setting 10
Bootstrap[286]: Time 43.682296 seconds, bootstrap likelihood -141536.093768, best rearrangement setting 13
Bootstrap[34]: Time 43.735756 seconds, bootstrap likelihood -137597.419248, best rearrangement setting 11
Bootstrap[370]: Time 44.382449 seconds, bootstrap likelihood -144045.272921, best rearrangement setting 10
Bootstrap[958]: Time 45.093350 seconds, bootstrap likelihood -137737.949117, best rearrangement setting 12
Bootstrap[874]: Time 45.493435 seconds, bootstrap likelihood -144215.303584, best rearrangement setting 15
Bootstrap[203]: Time 40.585527 seconds, bootstrap likelihood -142752.054974, best rearrangement setting 8
Bootstrap[539]: Time 42.357087 seconds, bootstrap likelihood -141686.892121, best rearrangement setting 8
Bootstrap[623]: Time 40.664185 seconds, bootstrap likelihood -145152.978334, best rearrangement setting 13
Bootstrap[455]: Time 42.953839 seconds, bootstrap likelihood -138010.849393, best rearrangement setting 13
Bootstrap[791]: Time 43.641761 seconds, bootstrap likelihood -142644.630487, best rearrangement setting 13
Bootstrap[707]: Time 41.209968 seconds, bootstrap likelihood -140294.768482, best rearrangement setting 7
Bootstrap[35]: Time 41.104319 seconds, bootstrap likelihood -139721.617933, best rearrangement setting 8
Bootstrap[371]: Time 41.398703 seconds, bootstrap likelihood -142314.205010, best rearrangement setting 8
Bootstrap[875]: Time 40.305502 seconds, bootstrap likelihood -139331.161833, best rearrangement setting 7
Bootstrap[119]: Time 45.714333 seconds, bootstrap likelihood -137986.437667, best rearrangement setting 14
Bootstrap[287]: Time 45.356807 seconds, bootstrap likelihood -137809.274964, best rearrangement setting 13
Bootstrap[959]: Time 44.380111 seconds, bootstrap likelihood -139868.819468, best rearrangement setting 13
Bootstrap[204]: Time 41.702127 seconds, bootstrap likelihood -141424.291343, best rearrangement setting 14
Bootstrap[792]: Time 36.672936 seconds, bootstrap likelihood -141851.524031, best rearrangement setting 5
Bootstrap[456]: Time 38.923288 seconds, bootstrap likelihood -141913.380233, best rearrangement setting 6
Bootstrap[624]: Time 39.582023 seconds, bootstrap likelihood -141482.140439, best rearrangement setting 11
Bootstrap[540]: Time 43.279367 seconds, bootstrap likelihood -145309.102920, best rearrangement setting 14
Bootstrap[708]: Time 41.398147 seconds, bootstrap likelihood -138080.429655, best rearrangement setting 8
Bootstrap[120]: Time 40.297813 seconds, bootstrap likelihood -139930.572615, best rearrangement setting 6
Bootstrap[36]: Time 42.787796 seconds, bootstrap likelihood -138882.292575, best rearrangement setting 9
Bootstrap[372]: Time 42.843436 seconds, bootstrap likelihood -140240.628905, best rearrangement setting 9
Bootstrap[876]: Time 43.681691 seconds, bootstrap likelihood -142527.186244, best rearrangement setting 13
Bootstrap[960]: Time 42.395831 seconds, bootstrap likelihood -137717.847994, best rearrangement setting 10
Bootstrap[288]: Time 44.783514 seconds, bootstrap likelihood -136643.069338, best rearrangement setting 11
Bootstrap[205]: Time 42.734799 seconds, bootstrap likelihood -140289.181913, best rearrangement setting 11
Bootstrap[625]: Time 40.532979 seconds, bootstrap likelihood -143657.515082, best rearrangement setting 12
Bootstrap[793]: Time 42.803694 seconds, bootstrap likelihood -139286.642108, best rearrangement setting 13
Bootstrap[457]: Time 43.289130 seconds, bootstrap likelihood -138559.992106, best rearrangement setting 12
Bootstrap[541]: Time 43.283754 seconds, bootstrap likelihood -140299.865974, best rearrangement setting 12
Bootstrap[709]: Time 42.999380 seconds, bootstrap likelihood -137536.885349, best rearrangement setting 12
Bootstrap[121]: Time 43.623949 seconds, bootstrap likelihood -135284.838760, best rearrangement setting 11
Bootstrap[37]: Time 43.830068 seconds, bootstrap likelihood -140847.312844, best rearrangement setting 11
Bootstrap[877]: Time 42.515741 seconds, bootstrap likelihood -143277.151725, best rearrangement setting 13
Bootstrap[373]: Time 44.207575 seconds, bootstrap likelihood -139362.914516, best rearrangement setting 12
Bootstrap[961]: Time 43.662131 seconds, bootstrap likelihood -137262.808812, best rearrangement setting 13
Bootstrap[289]: Time 44.259627 seconds, bootstrap likelihood -137065.235442, best rearrangement setting 12
Bootstrap[206]: Time 38.238008 seconds, bootstrap likelihood -143728.665920, best rearrangement setting 7
Bootstrap[710]: Time 38.149090 seconds, bootstrap likelihood -137690.506959, best rearrangement setting 5
Bootstrap[878]: Time 38.249350 seconds, bootstrap likelihood -138024.032656, best rearrangement setting 5
Bootstrap[542]: Time 39.393424 seconds, bootstrap likelihood -144984.001548, best rearrangement setting 6
Bootstrap[374]: Time 39.474001 seconds, bootstrap likelihood -143185.386620, best rearrangement setting 7
Bootstrap[626]: Time 39.554602 seconds, bootstrap likelihood -142611.738089, best rearrangement setting 11
Bootstrap[38]: Time 41.542552 seconds, bootstrap likelihood -135707.686960, best rearrangement setting 8
Bootstrap[794]: Time 41.630936 seconds, bootstrap likelihood -140280.523634, best rearrangement setting 10
Bootstrap[458]: Time 42.968071 seconds, bootstrap likelihood -142951.669537, best rearrangement setting 12
Bootstrap[962]: Time 43.314309 seconds, bootstrap likelihood -137704.196636, best rearrangement setting 10
Bootstrap[290]: Time 44.231847 seconds, bootstrap likelihood -136336.513000, best rearrangement setting 13
Bootstrap[122]: Time 45.289542 seconds, bootstrap likelihood -136897.730804, best rearrangement setting 13
Bootstrap[207]: Time 36.861277 seconds, bootstrap likelihood -139980.537945, best rearrangement setting 6
Bootstrap[711]: Time 38.342364 seconds, bootstrap likelihood -137470.719156, best rearrangement setting 6
Bootstrap[627]: Time 41.429775 seconds, bootstrap likelihood -140913.052753, best rearrangement setting 15
Bootstrap[879]: Time 42.776968 seconds, bootstrap likelihood -140439.437054, best rearrangement setting 10
Bootstrap[375]: Time 42.273197 seconds, bootstrap likelihood -139343.367642, best rearrangement setting 9
Bootstrap[795]: Time 40.887084 seconds, bootstrap likelihood -137503.227393, best rearrangement setting 8
Bootstrap[543]: Time 44.322205 seconds, bootstrap likelihood -143743.542136, best rearrangement setting 13
Bootstrap[291]: Time 41.275270 seconds, bootstrap likelihood -137606.901749, best rearrangement setting 8
Bootstrap[39]: Time 44.080087 seconds, bootstrap likelihood -136726.223176, best rearrangement setting 13
Bootstrap[459]: Time 42.974542 seconds, bootstrap likelihood -139385.430834, best rearrangement setting 11
Bootstrap[963]: Time 44.449867 seconds, bootstrap likelihood -143016.507076, best rearrangement setting 12
Bootstrap[123]: Time 45.026603 seconds, bootstrap likelihood -138649.129957, best rearrangement setting 15
Bootstrap[208]: Time 52.779041 seconds, bootstrap likelihood -139650.252239, best rearrangement setting 13
Bootstrap[712]: Time 58.024827 seconds, bootstrap likelihood -137144.730665, best rearrangement setting 14
Bootstrap[628]: Time 55.094528 seconds, bootstrap likelihood -140797.782425, best rearrangement setting 14
Bootstrap[880]: Time 55.482438 seconds, bootstrap likelihood -142386.879079, best rearrangement setting 14
Bootstrap[460]: Time 52.355860 seconds, bootstrap likelihood -141610.012061, best rearrangement setting 13
Bootstrap[544]: Time 56.931899 seconds, bootstrap likelihood -143590.912109, best rearrangement setting 13
Bootstrap[376]: Time 58.913674 seconds, bootstrap likelihood -143874.147491, best rearrangement setting 13
Bootstrap[292]: Time 56.597584 seconds, bootstrap likelihood -140628.790029, best rearrangement setting 13
Bootstrap[796]: Time 59.881260 seconds, bootstrap likelihood -141604.623221, best rearrangement setting 14
Bootstrap[964]: Time 57.470526 seconds, bootstrap likelihood -138707.835995, best rearrangement setting 14
Bootstrap[40]: Time 60.286588 seconds, bootstrap likelihood -140254.632043, best rearrangement setting 13
Bootstrap[124]: Time 56.402534 seconds, bootstrap likelihood -135701.415593, best rearrangement setting 13
Bootstrap[209]: Time 35.899977 seconds, bootstrap likelihood -143666.818739, best rearrangement setting 5
Bootstrap[629]: Time 39.479351 seconds, bootstrap likelihood -141843.655949, best rearrangement setting 9
Bootstrap[881]: Time 40.479023 seconds, bootstrap likelihood -142659.957568, best rearrangement setting 8
Bootstrap[713]: Time 42.926065 seconds, bootstrap likelihood -137070.975786, best rearrangement setting 12
Bootstrap[545]: Time 38.098765 seconds, bootstrap likelihood -143831.100547, best rearrangement setting 6
Bootstrap[797]: Time 37.963061 seconds, bootstrap likelihood -139514.880212, best rearrangement setting 5
Bootstrap[461]: Time 42.521565 seconds, bootstrap likelihood -141644.612925, best rearrangement setting 14
Bootstrap[377]: Time 42.020942 seconds, bootstrap likelihood -142871.329393, best rearrangement setting 11
Bootstrap[293]: Time 41.822573 seconds, bootstrap likelihood -138838.833394, best rearrangement setting 8
Bootstrap[965]: Time 41.480531 seconds, bootstrap likelihood -138269.105630, best rearrangement setting 11
Bootstrap[41]: Time 42.026486 seconds, bootstrap likelihood -138329.891253, best rearrangement setting 10
Bootstrap[125]: Time 44.165207 seconds, bootstrap likelihood -141231.896305, best rearrangement setting 13
Bootstrap[42]: Time 36.862768 seconds, bootstrap likelihood -137395.891159, best rearrangement setting 5
Bootstrap[546]: Time 38.426958 seconds, bootstrap likelihood -138827.059435, best rearrangement setting 6
Bootstrap[630]: Time 41.258711 seconds, bootstrap likelihood -137645.460786, best rearrangement setting 15
Bootstrap[882]: Time 41.565249 seconds, bootstrap likelihood -143463.085467, best rearrangement setting 10
Bootstrap[462]: Time 41.690996 seconds, bootstrap likelihood -142340.062783, best rearrangement setting 8
Bootstrap[966]: Time 41.919652 seconds, bootstrap likelihood -139343.530632, best rearrangement setting 9
Bootstrap[294]: Time 42.521735 seconds, bootstrap likelihood -136369.057883, best rearrangement setting 11
Bootstrap[378]: Time 42.805072 seconds, bootstrap likelihood -143877.585722, best rearrangement setting 10
Bootstrap[210]: Time 43.432064 seconds, bootstrap likelihood -142047.505089, best rearrangement setting 13
Bootstrap[798]: Time 43.480761 seconds, bootstrap likelihood -139976.684827, best rearrangement setting 12
Bootstrap[714]: Time 43.672085 seconds, bootstrap likelihood -138926.218166, best rearrangement setting 14
Bootstrap[126]: Time 45.415171 seconds, bootstrap likelihood -137115.127476, best rearrangement setting 15
Bootstrap[799]: Time 36.585246 seconds, bootstrap likelihood -142110.527992, best rearrangement setting 5
Bootstrap[211]: Time 38.322665 seconds, bootstrap likelihood -140802.508319, best rearrangement setting 7
Bootstrap[463]: Time 40.579060 seconds, bootstrap likelihood -138491.697208, best rearrangement setting 8
Bootstrap[43]: Time 45.609992 seconds, bootstrap likelihood -136805.658802, best rearrangement setting 14
Bootstrap[547]: Time 45.512858 seconds, bootstrap likelihood -141551.972064, best rearrangement setting 15
Bootstrap[631]: Time 42.984977 seconds, bootstrap likelihood -143537.714248, best rearrangement setting 12
Bootstrap[715]: Time 40.764413 seconds, bootstrap likelihood -140690.623054, best rearrangement setting 8
Bootstrap[883]: Time 43.582538 seconds, bootstrap likelihood -141479.238257, best rearrangement setting 12
Bootstrap[967]: Time 44.046495 seconds, bootstrap likelihood -139303.197297, best rearrangement setting 9
Bootstrap[295]: Time 43.458127 seconds, bootstrap likelihood -138737.906980, best rearrangement setting 14
Bootstrap[379]: Time 43.388813 seconds, bootstrap likelihood -139695.023777, best rearrangement setting 11
Bootstrap[127]: Time 42.067355 seconds, bootstrap likelihood -136230.802220, best rearrangement setting 10
Bootstrap[212]: Time 38.565053 seconds, bootstrap likelihood -142137.549435, best rearrangement setting 7
Bootstrap[464]: Time 39.096589 seconds, bootstrap likelihood -140560.257251, best rearrangement setting 6
Bootstrap[800]: Time 41.300723 seconds, bootstrap likelihood -142166.754159, best rearrangement setting 9
Bootstrap[968]: Time 37.533636 seconds, bootstrap likelihood -138773.624626, best rearrangement setting 5
Bootstrap[716]: Time 39.193791 seconds, bootstrap likelihood -136605.485393, best rearrangement setting 6
Bootstrap[44]: Time 42.463221 seconds, bootstrap likelihood -137799.366953, best rearrangement setting 10
Bootstrap[548]: Time 42.765299 seconds, bootstrap likelihood -142683.403292, best rearrangement setting 10
Bootstrap[632]: Time 43.126729 seconds, bootstrap likelihood -139853.540035, best rearrangement setting 13
Bootstrap[296]: Time 43.622393 seconds, bootstrap likelihood -137753.622702, best rearrangement setting 10
Bootstrap[884]: Time 44.881445 seconds, bootstrap likelihood -143186.632430, best rearrangement setting 13
Bootstrap[380]: Time 45.025605 seconds, bootstrap likelihood -141338.625464, best rearrangement setting 14
Bootstrap[128]: Time 43.857094 seconds, bootstrap likelihood -135134.170979, best rearrangement setting 14
Bootstrap[213]: Time 37.020156 seconds, bootstrap likelihood -140338.874841, best rearrangement setting 6
Bootstrap[465]: Time 42.172554 seconds, bootstrap likelihood -141851.927388, best rearrangement setting 9
Bootstrap[801]: Time 42.250665 seconds, bootstrap likelihood -140107.526976, best rearrangement setting 13
Bootstrap[717]: Time 43.616347 seconds, bootstrap likelihood -141618.911461, best rearrangement setting 12
Bootstrap[129]: Time 35.997044 seconds, bootstrap likelihood -135998.336190, best rearrangement setting 5
Bootstrap[969]: Time 45.367834 seconds, bootstrap likelihood -137110.613206, best rearrangement setting 15
Bootstrap[633]: Time 41.516214 seconds, bootstrap likelihood -141743.378838, best rearrangement setting 11
Bootstrap[549]: Time 42.683827 seconds, bootstrap likelihood -144611.077959, best rearrangement setting 10
Bootstrap[45]: Time 45.359641 seconds, bootstrap likelihood -136449.943860, best rearrangement setting 15
Bootstrap[297]: Time 40.733684 seconds, bootstrap likelihood -137486.725559, best rearrangement setting 7
Bootstrap[381]: Time 40.476338 seconds, bootstrap likelihood -141817.595606, best rearrangement setting 8
Bootstrap[885]: Time 43.631954 seconds, bootstrap likelihood -139781.833208, best rearrangement setting 14


Stopped Rapid BS search after 552 replicates with MRE-based Bootstopping criterion
WRF Average of 100 random splits: 2.495904
Overall Time for 552 Rapid Bootstraps 2117.663877 seconds
Average Time per Rapid Bootstrap 3.836348 seconds

Starting ML Search ...

Fast ML search on Process 8: Time 409.975508 seconds

Fast ML search on Process 4: Time 495.582566 seconds

Fast ML search on Process 3: Time 566.190320 seconds

Fast ML search on Process 5: Time 655.871655 seconds

Fast ML search on Process 7: Time 724.209436 seconds

Fast ML search on Process 2: Time 737.623125 seconds

Fast ML search on Process 1: Time 741.147450 seconds

Fast ML optimization finished

Fast ML search on Process 0: Time 758.301937 seconds

Fast ML search on Process 6: Time 777.866055 seconds

Fast ML search on Process 9: Time 804.910299 seconds

Fast ML search on Process 10: Time 805.167544 seconds

Fast ML search on Process 11: Time 1023.869670 seconds

Slow ML Search 252 Likelihood: -147075.775794
Slow ML search on Process 3: Time 553.405115 seconds
Slow ML Search 84 Likelihood: -147077.806359
Slow ML search on Process 1: Time 479.845206 seconds
Slow ML Search 0 Likelihood: -147084.029791
Slow ML optimization finished

Slow ML search on Process 0: Time 593.479161 seconds
Slow ML Search 672 Likelihood: -147065.848828
Slow ML search on Process 8: Time 969.129645 seconds
Slow ML Search 336 Likelihood: -147078.761610
Slow ML search on Process 4: Time 911.249181 seconds
Slow ML Search 420 Likelihood: -147102.528648
Slow ML search on Process 5: Time 957.660592 seconds
Slow ML Search 168 Likelihood: -147077.247049
Slow ML search on Process 2: Time 894.592199 seconds
Slow ML Search 840 Likelihood: -147049.063358
Slow ML search on Process 10: Time 838.917950 seconds
Slow ML Search 756 Likelihood: -147042.892604
Slow ML search on Process 9: Time 901.567367 seconds
Thorough ML search on Process 3: Time 636.928140 seconds
Slow ML Search 924 Likelihood: -147096.889065
Slow ML search on Process 11: Time 739.199467 seconds
Thorough ML search on Process 1: Time 652.951976 seconds
Slow ML Search 588 Likelihood: -147072.001893
Slow ML search on Process 7: Time 1158.103646 seconds
Slow ML Search 504 Likelihood: -147070.788314
Slow ML search on Process 6: Time 1127.438561 seconds
Thorough ML search on Process 0: Time 633.968051 seconds
Thorough ML search on Process 8: Time 639.253090 seconds
Thorough ML search on Process 4: Time 640.010357 seconds
Thorough ML search on Process 2: Time 609.483408 seconds
Thorough ML search on Process 5: Time 638.127877 seconds
Thorough ML search on Process 10: Time 629.426609 seconds
Thorough ML search on Process 9: Time 643.647916 seconds
Thorough ML search on Process 11: Time 644.371753 seconds
Thorough ML search on Process 7: Time 628.718241 seconds
Thorough ML search on Process 6: Time 624.455186 seconds

Final ML Optimization Likelihood: -147034.224678

Model Information:

Model Parameters of Partition 0, Name: ITS, Type of Data: DNA
alpha: 0.379249
Tree-Length: 14.885478
rate A <-> C: 0.948490
rate A <-> G: 1.263998
rate A <-> T: 1.014500
rate C <-> G: 0.516624
rate C <-> T: 1.820570
rate G <-> T: 1.000000

freq pi(A): 0.217375
freq pi(C): 0.276952
freq pi(G): 0.280743
freq pi(T): 0.224930

Model Parameters of Partition 1, Name: matK, Type of Data: DNA
alpha: 0.765295
Tree-Length: 14.885478
rate A <-> C: 1.163986
rate A <-> G: 2.052012
rate A <-> T: 0.300396
rate C <-> G: 0.817928
rate C <-> T: 1.852332
rate G <-> T: 1.000000

freq pi(A): 0.315366
freq pi(C): 0.172058
freq pi(G): 0.147263
freq pi(T): 0.365313

Model Parameters of Partition 2, Name: rbcL, Type of Data: DNA
alpha: 0.273495
Tree-Length: 14.885478
rate A <-> C: 0.847219
rate A <-> G: 2.909095
rate A <-> T: 0.237209
rate C <-> G: 0.489971
rate C <-> T: 1.906223
rate G <-> T: 1.000000

freq pi(A): 0.281970
freq pi(C): 0.210860
freq pi(G): 0.238177
freq pi(T): 0.268993

Model Parameters of Partition 3, Name: atpB, Type of Data: DNA
alpha: 0.421883
Tree-Length: 14.885478
rate A <-> C: 0.878134
rate A <-> G: 3.040963
rate A <-> T: 0.450798
rate C <-> G: 0.649441
rate C <-> T: 1.457648
rate G <-> T: 1.000000

freq pi(A): 0.274618
freq pi(C): 0.258167
freq pi(G): 0.176097
freq pi(T): 0.291118

Model Parameters of Partition 4, Name: ndhF, Type of Data: DNA
alpha: 0.487630
Tree-Length: 14.885478
rate A <-> C: 1.665201
rate A <-> G: 3.058736
rate A <-> T: 0.432378
rate C <-> G: 1.359937
rate C <-> T: 2.727159
rate G <-> T: 1.000000

freq pi(A): 0.269395
freq pi(C): 0.167581
freq pi(G): 0.174943
freq pi(T): 0.388081

Model Parameters of Partition 5, Name: trnTLF, Type of Data: DNA
alpha: 1.273554
Tree-Length: 14.885478
rate A <-> C: 1.226802
rate A <-> G: 1.892424
rate A <-> T: 1.067986
rate C <-> G: 0.534930
rate C <-> T: 2.137351
rate G <-> T: 1.000000

freq pi(A): 0.322540
freq pi(C): 0.190084
freq pi(G): 0.208118
freq pi(T): 0.279257


ML search took 2529.863070 secs or 0.702740 hours

Combined Bootstrap and ML search took 4647.523876 secs or 1.290979 hours

Drawing Bootstrap Support Values on best-scoring ML tree ...



Found 1 tree in File /projects/ps-ngbt/backend/comet_workspace/NGBW-JOB-RAXMLHPC8_XSEDE-6808A8D97389464392FDFB7A532B3FEE/RAxML_bestTree.sawtooth.concat.autoMRE.ML



Found 1 tree in File /projects/ps-ngbt/backend/comet_workspace/NGBW-JOB-RAXMLHPC8_XSEDE-6808A8D97389464392FDFB7A532B3FEE/RAxML_bestTree.sawtooth.concat.autoMRE.ML

Program execution info written to /projects/ps-ngbt/backend/comet_workspace/NGBW-JOB-RAXMLHPC8_XSEDE-6808A8D97389464392FDFB7A532B3FEE/RAxML_info.sawtooth.concat.autoMRE.ML
All 552 bootstrapped trees written to: /projects/ps-ngbt/backend/comet_workspace/NGBW-JOB-RAXMLHPC8_XSEDE-6808A8D97389464392FDFB7A532B3FEE/RAxML_bootstrap.sawtooth.concat.autoMRE.ML

Best-scoring ML tree written to: /projects/ps-ngbt/backend/comet_workspace/NGBW-JOB-RAXMLHPC8_XSEDE-6808A8D97389464392FDFB7A532B3FEE/RAxML_bestTree.sawtooth.concat.autoMRE.ML

Best-scoring ML tree with support values written to: /projects/ps-ngbt/backend/comet_workspace/NGBW-JOB-RAXMLHPC8_XSEDE-6808A8D97389464392FDFB7A532B3FEE/RAxML_bipartitions.sawtooth.concat.autoMRE.ML

Best-scoring ML tree with support values as branch labels written to: /projects/ps-ngbt/backend/comet_workspace/NGBW-JOB-RAXMLHPC8_XSEDE-6808A8D97389464392FDFB7A532B3FEE/RAxML_bipartitionsBranchLabels.sawtooth.concat.autoMRE.ML

Overall execution time for full ML analysis: 4648.189544 secs or 1.291164 hours or 0.053798 days

